---
title: "Introduction to minir"
author: "Zhuoer Dong"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to minir}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", cache = TRUE)
```

```{r}
library(pgmcs)

suppressWarnings(RNGversion('3.5.2'))
```

# Command line usage

## Figure 20.8 at P671. 

Initial population are all heterozygotes.

```{r}
set.seed(13);
demo_population_simulation(6, 30, c(0, 10, 0), c(1, 1, 1), "Small population: Lots of genetic drift");
```

```{r}
set.seed(0);
demo_population_simulation(6, 30, c(0, 500, 0), c(1, 1, 1), "Large population: Little genetic drift");
```

## Figure 20.13 at P676. 

499*bb + 1*Bb; WBB = 1.0, WBb = 1.0, Wbb = 0.98 (adjusted to 0.97)

```{r}
set.seed(57);
demo_population_simulation(6, 900, c(0, 1, 499), c(1,1,0.97), "Natural selection together with genetic
drift")
```

```{r}
set.seed(885);
demo_population_simulation(6, 900, c(0, 1, 499), c(1,1,0.97), "Natural selection together with genetic
drift")
```

## Draft vs Selection

```{r}
set.seed(0);
demo_population_simulation(100, 250, c(0, 490, 10), c(1, 1, 1), 'drift')
demo_population_simulation(100, 250, c(0, 490, 10), c(1, 1, 0.95), 'select A')
```

# Shiny App

```r
shiny::runApp(system.file('shiny/population-genetics-monte-carlo-simulation', package = 'pgmcs'))
shiny::runApp(system.file('shiny/population-genetics-monte-carlo-simulation2', package = 'pgmcs'))
```

----------------------------------

If you get interested in these figures, but feel scared about the code, please refer to `vignette('beginner')`
